name: Docker tests
run-name: ${{ github.actor }} is running the test schedules.
on:
  # Run at midnight (00:00) and noon (12:00) UTC every day
  schedule:
    - cron: '0 0 * * *'    # Midnight UTC
    - cron: '0 12 * * *'   # Noon UTC

  # Run on any push to any branch
  ## push:
    ## branches:
      ## - '**'  # Matches all branches

  # Run when a pull request is opened, synchronized, or reopened
  ## pull_request:
    ## types: [opened, synchronize, reopened]
    
jobs:
  run-scripts:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        pgver: [15, 16, 17]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout platform_test
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Verify patches directory exists
      run: |
        ls -la
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build --build-arg PGVER=${{ matrix.pgver }} -t platform_test docker/
   
    - name: Run Docker Container
      run: |
        docker run -d --name platform_test -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 platform_test

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is ready!"
              exit 0
          fi
          echo "PostgreSQL is not ready yet. Retrying in 5 seconds..."
          sleep 5
          done
          echo "PostgreSQL did not become ready in time. Exiting."
          exit 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt install -y postgresql-client \
            libpq-dev \
            python3-dev \
            python3-psycopg2 \
            python3-dotenv

   
